class Constants():
    #define PSO constants
    PSO_SWARM_SIZE = 30
    PSO_MAX_ITERATIONS = 100
    #define NSGA2 constants
    NSGA2_NUM_INDIVIDUALS = 30
    NSGA2_NUM_GENERATIONS = 100
    NSGA2_NUM_GENES_MUTATING = 5
    NSGA2_MUTATION_STRENGTH = 1
    #define SPEA2 Constants
    SPEA2_INITIAL_POPULATION = 30
    SPEA2_MAX_ARCHIVE_SIZE = 30
    SPEA2_MAX_GENERATIONS = 100
    #define Flower Constants
    FP_MAX_GENERATIONS = 100
    FP_NUMBER_OF_FLOWERS = 100
    FP_SWITCH_PROBABILITY = 0.5
    #define Bee Colony constraints
    BC_POPULATION_SIZE = 30
    BC_MAX_CYCLE_NUMBER = 100
    BC_LIMIT = 50
    
